In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
import geopandas as gpd

In [9]:
dfR = pd.read_csv('Dataset .csv')
dfR.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [10]:
dfR.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [11]:
dfR.duplicated().sum()

np.int64(0)

In [12]:
dfR['Restaurant Name'].duplicated().sum()

np.int64(2105)

In [13]:
dfR['Restaurant Name'].value_counts()

Restaurant Name
Cafe Coffee Day             83
Domino's Pizza              79
Subway                      63
Green Chick Chop            51
McDonald's                  48
                            ..
HotMess                      1
Healthy Routes               1
Fuji Japanese Restaurant     1
Fa Yian                      1
Unplugged Courtyard          1
Name: count, Length: 7446, dtype: int64

In [14]:
dfR = dfR.sort_values(by=['Restaurant Name','Aggregate rating'],ascending=False)
dfR.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9523,6000871,�ukura��a Sofras۱,208,Ankara,"Emek Mahallesi, Bosna Hersek Caddesi, No 22/C,...",Emek,"Emek, Ankara",32.818833,39.916667,"Kebab, Izgara",...,Turkish Lira(TL),No,No,No,No,3,4.4,Green,Very Good,296
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,"North Indian, Chinese, Italian, Continental",...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
9334,7100938,wagamama,148,Wellington City,"33 Customhouse Quay, Wellington Central, Welli...",Wellington Central,"Wellington Central, Wellington City",174.779224,-41.283034,"Japanese, Asian",...,NewZealand($),No,No,No,No,4,3.7,Yellow,Good,131
9454,6401789,tashas,189,Cape Town,"Ground Level, Victoria Wharf, V & A Waterfront...",V & A Waterfront,"V & A Waterfront, Cape Town",18.421341,-33.902336,"Cafe, Mediterranean",...,Rand(R),No,No,No,No,4,4.1,Green,Very Good,374
4659,18361747,t Lounge by Dilmah,1,New Delhi,"Flat 44, 1st Floor, Khan Market, New Delhi",Khan Market,"Khan Market, New Delhi",77.227133,28.601087,"Cafe, Tea, Desserts",...,Indian Rupees(Rs.),No,No,No,No,2,3.6,Yellow,Good,34

In [15]:
#removing duplicate entries of same restaurant name
dfR = dfR.drop_duplicates('Restaurant Name',keep='first')
dfR

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9523,6000871,�ukura��a Sofras۱,208,Ankara,"Emek Mahallesi, Bosna Hersek Caddesi, No 22/C,...",Emek,"Emek, Ankara",32.818833,39.916667,"Kebab, Izgara",...,Turkish Lira(TL),No,No,No,No,3,4.4,Green,Very Good,296
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,"North Indian, Chinese, Italian, Continental",...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
9334,7100938,wagamama,148,Wellington City,"33 Customhouse Quay, Wellington Central, Welli...",Wellington Central,"Wellington Central, Wellington City",174.779224,-41.283034,"Japanese, Asian",...,NewZealand($),No,No,No,No,4,3.7,Yellow,Good,131
9454,6401789,tashas,189,Cape Town,"Ground Level, Victoria Wharf, V & A Waterfront...",V & A Waterfront,"V & A Waterfront, Cape Town",18.421341,-33.902336,"Cafe, Mediterranean",...,Rand(R),No,No,No,No,4,4.1,Green,Very Good,374
4659,18361747,t Lounge by Dilmah,1,New Delhi,"Flat 44, 1st Floor, Khan Market, New Delhi",Khan Market,"Khan Market, New Delhi",77.227133,28.601087,"Cafe, Tea, Desserts",...,Indian Rupees(Rs.),No,No,No,No,2,3.6,Yellow,Good,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8692,18317511,#Urban Caf��,1,Noida,"LG-06, Amrapali Arcade 1, Amrapali Sapphire, S...",Sector 45,"Sector 45, Noida",77.344153,28.548574,"North Indian, Chinese, Italian",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.3,Orange,Average,49
6998,18336489,#OFF Campus,1,New Delhi,"284, Opposite Sri Venkateshwara College, Satya...",Satyaniketan,"Satyaniketan, New Delhi",77.168737,28.588521,"Cafe, Continental, Italian, Fast Food",...,Indian Rupees(Rs.),Yes,Yes,No,No,2,3.7,Yellow,Good,216
2613,18311951,#InstaFreeze,1,New Delhi,"B-17, Alaknanda Shopping Complex, Alaknanda, N...",Alaknanda,"Alaknanda, New Delhi",77.253694,28.525420,Ice Cream,...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,2
9148,18378803,#Dilliwaala6,1,Puducherry,"6, Rue De La Marine, White Town, Puducherry",White Town,"White Town, Puducherry",79.834810,11.936532,North Indian,...,Indian Rupees(Rs.),No,No,No,No,3,3.7,Yellow,Good,124
2459,3100446,#45,1,Mangalore,"Ground Floor, Trinity Commercial Complex, Near...",Attavar,"Attavar, Mangalore",0.000000,0.000000,Cafe,...,Indian Rupees(Rs.),No,No,No,No,2,3.6,Yellow,Good,209

In [16]:
dfR['Restaurant Name'].value_counts()

Restaurant Name
#45                          1
�ukura��a Sofras۱            1
{Niche} - Cafe & Bar         1
wagamama                     1
tashas                       1
                            ..
eastWEST - Radisson Hotel    1
feel ALIVE                   1
hug!                         1
iGNiTE                       1
iKitchen                     1
Name: count, Length: 7446, dtype: int64

In [17]:
dfR = dfR[dfR['Aggregate rating']>3.9]
dfR

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9523,6000871,�ukura��a Sofras۱,208,Ankara,"Emek Mahallesi, Bosna Hersek Caddesi, No 22/C,...",Emek,"Emek, Ankara",32.818833,39.916667,"Kebab, Izgara",...,Turkish Lira(TL),No,No,No,No,3,4.4,Green,Very Good,296
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,"North Indian, Chinese, Italian, Continental",...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
9454,6401789,tashas,189,Cape Town,"Ground Level, Victoria Wharf, V & A Waterfront...",V & A Waterfront,"V & A Waterfront, Cape Town",18.421341,-33.902336,"Cafe, Mediterranean",...,Rand(R),No,No,No,No,4,4.1,Green,Very Good,374
9385,6113857,sketch Gallery,215,London,"sketch, 9 Conduit Street, Mayfair, London W1S 2XG","Conduit Street, Mayfair","Conduit Street, Mayfair, London",-0.141557,51.512669,"British, Contemporary",...,Pounds(��),No,No,No,No,4,4.5,Dark Green,Excellent,148
1837,18418247,feel ALIVE,1,Gurgaon,"SCO 53, 2nd Floor, Main Market, Sector 29, Gur...",Sector 29,"Sector 29, Gurgaon",77.064137,28.467926,"North Indian, American, Asian, Biryani",...,Indian Rupees(Rs.),Yes,No,No,No,3,4.7,Dark Green,Excellent,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,18408054,19 Flavours Biryani,1,Gurgaon,"Global Foyer Mall, Sector 43, Golf Course Road...","Global Foyer Mall, Golf Course Road","Global Foyer Mall, Golf Course Road, Gurgaon",77.095432,28.460444,"Mughlai, Hyderabadi",...,Indian Rupees(Rs.),No,Yes,No,No,2,4.1,Green,Very Good,84
2484,18233317,145 Kala Ghoda,1,Mumbai,"145, Kala Ghoda, Fort, Mumbai",Fort,"Fort, Mumbai",72.832585,18.927584,"Fast Food, Beverages, Desserts",...,Indian Rupees(Rs.),No,No,No,No,3,4.2,Green,Very Good,1606
2292,2100784,11th Avenue Cafe Bistro,1,Guwahati,"Opposite Assam State Museum, Dighalipukhuri, T...",Uzan Bazaar,"Uzan Bazaar, Guwahati",91.752314,26.186001,"Cafe, American, Italian, Continental",...,Indian Rupees(Rs.),No,No,No,No,2,4.1,Green,Very Good,377
751,2600031,10 Downing Street,1,Bhopal,"Third Floor, DB City Mall, Maharana Pratap Nag...","DB City, Maharana Pratap Nagar","DB City, Maharana Pratap Nagar, Bhopal",77.429989,23.232357,"North Indian, Chinese",...,Indian Rupees(Rs.),No,No,No,No,3,4.0,Green,Very Good,257
351,17057397,'Ohana,216,Orlando,"1600 Seven Seas Drive, Lake Buena Vista, FL 32830",Disney World Area,"Disney World Area, Orlando",-81.585226,28.405437,Hawaiian,...,Dollar($),No,No,No,No,3,4.5,Dark Green,Excellent,1151

In [18]:

#splitting cuisines into list
dfR['Cuisines'] = dfR['Cuisines'].str.split(', ')
dfR

<ipython-input-18-42e347602abc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfR['Cuisines'] = dfR['Cuisines'].str.split(', ')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9523,6000871,�ukura��a Sofras۱,208,Ankara,"Emek Mahallesi, Bosna Hersek Caddesi, No 22/C,...",Emek,"Emek, Ankara",32.818833,39.916667,"[Kebab, Izgara]",...,Turkish Lira(TL),No,No,No,No,3,4.4,Green,Very Good,296
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,"[North Indian, Chinese, Italian, Continental]",...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
9454,6401789,tashas,189,Cape Town,"Ground Level, Victoria Wharf, V & A Waterfront...",V & A Waterfront,"V & A Waterfront, Cape Town",18.421341,-33.902336,"[Cafe, Mediterranean]",...,Rand(R),No,No,No,No,4,4.1,Green,Very Good,374
9385,6113857,sketch Gallery,215,London,"sketch, 9 Conduit Street, Mayfair, London W1S 2XG","Conduit Street, Mayfair","Conduit Street, Mayfair, London",-0.141557,51.512669,"[British, Contemporary]",...,Pounds(��),No,No,No,No,4,4.5,Dark Green,Excellent,148
1837,18418247,feel ALIVE,1,Gurgaon,"SCO 53, 2nd Floor, Main Market, Sector 29, Gur...",Sector 29,"Sector 29, Gurgaon",77.064137,28.467926,"[North Indian, American, Asian, Biryani]",...,Indian Rupees(Rs.),Yes,No,No,No,3,4.7,Dark Green,Excellent,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,18408054,19 Flavours Biryani,1,Gurgaon,"Global Foyer Mall, Sector 43, Golf Course Road...","Global Foyer Mall, Golf Course Road","Global Foyer Mall, Golf Course Road, Gurgaon",77.095432,28.460444,"[Mughlai, Hyderabadi]",...,Indian Rupees(Rs.),No,Yes,No,No,2,4.1,Green,Very Good,84
2484,18233317,145 Kala Ghoda,1,Mumbai,"145, Kala Ghoda, Fort, Mumbai",Fort,"Fort, Mumbai",72.832585,18.927584,"[Fast Food, Beverages, Desserts]",...,Indian Rupees(Rs.),No,No,No,No,3,4.2,Green,Very Good,1606
2292,2100784,11th Avenue Cafe Bistro,1,Guwahati,"Opposite Assam State Museum, Dighalipukhuri, T...",Uzan Bazaar,"Uzan Bazaar, Guwahati",91.752314,26.186001,"[Cafe, American, Italian, Continental]",...,Indian Rupees(Rs.),No,No,No,No,2,4.1,Green,Very Good,377
751,2600031,10 Downing Street,1,Bhopal,"Third Floor, DB City Mall, Maharana Pratap Nag...","DB City, Maharana Pratap Nagar","DB City, Maharana Pratap Nagar, Bhopal",77.429989,23.232357,"[North Indian, Chinese]",...,Indian Rupees(Rs.),No,No,No,No,3,4.0,Green,Very Good,257
351,17057397,'Ohana,216,Orlando,"1600 Seven Seas Drive, Lake Buena Vista, FL 32830",Disney World Area,"Disney World Area, Orlando",-81.585226,28.405437,[Hawaiian],...,Dollar($),No,No,No,No,3,4.5,Dark Green,Excellent,1151

In [19]:
dfR = dfR.explode('Cuisines')
dfR

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9523,6000871,�ukura��a Sofras۱,208,Ankara,"Emek Mahallesi, Bosna Hersek Caddesi, No 22/C,...",Emek,"Emek, Ankara",32.818833,39.916667,Kebab,...,Turkish Lira(TL),No,No,No,No,3,4.4,Green,Very Good,296
9523,6000871,�ukura��a Sofras۱,208,Ankara,"Emek Mahallesi, Bosna Hersek Caddesi, No 22/C,...",Emek,"Emek, Ankara",32.818833,39.916667,Izgara,...,Turkish Lira(TL),No,No,No,No,3,4.4,Green,Very Good,296
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,North Indian,...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,Chinese,...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
3120,18222559,{Niche} - Cafe & Bar,1,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...",Connaught Place,"Connaught Place, New Delhi",77.222507,28.631516,Italian,...,Indian Rupees(Rs.),Yes,No,No,No,3,4.1,Green,Very Good,492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2292,2100784,11th Avenue Cafe Bistro,1,Guwahati,"Opposite Assam State Museum, Dighalipukhuri, T...",Uzan Bazaar,"Uzan Bazaar, Guwahati",91.752314,26.186001,Italian,...,Indian Rupees(Rs.),No,No,No,No,2,4.1,Green,Very Good,377
2292,2100784,11th Avenue Cafe Bistro,1,Guwahati,"Opposite Assam State Museum, Dighalipukhuri, T...",Uzan Bazaar,"Uzan Bazaar, Guwahati",91.752314,26.186001,Continental,...,Indian Rupees(Rs.),No,No,No,No,2,4.1,Green,Very Good,377
751,2600031,10 Downing Street,1,Bhopal,"Third Floor, DB City Mall, Maharana Pratap Nag...","DB City, Maharana Pratap Nagar","DB City, Maharana Pratap Nagar, Bhopal",77.429989,23.232357,North Indian,...,Indian Rupees(Rs.),No,No,No,No,3,4.0,Green,Very Good,257
751,2600031,10 Downing Street,1,Bhopal,"Third Floor, DB City Mall, Maharana Pratap Nag...","DB City, Maharana Pratap Nagar","DB City, Maharana Pratap Nagar, Bhopal",77.429989,23.232357,Chinese,...,Indian Rupees(Rs.),No,No,No,No,3,4.0,Green,Very Good,257
351,17057397,'Ohana,216,Orlando,"1600 Seven Seas Drive, Lake Buena Vista, FL 32830",Disney World Area,"Disney World Area, Orlando",-81.585226,28.405437,Hawaiian,...,Dollar($),No,No,No,No,3,4.5,Dark Green,Excellent,1151

In [20]:

dfR['Cuisines'].value_counts()

Cuisines
North Indian      270
Italian           237
Chinese           200
Continental       199
Cafe              177
                 ...
Fish and Chips      1
Cuban               1
Mangalorean         1
New American        1
Bubble Tea          1
Name: count, Length: 128, dtype: int64

In [21]:
restoXcuisines = pd.crosstab(dfR['Restaurant Name'], dfR['Cuisines'])

In [22]:
restoXcuisines

Cuisines,Afghani,African,American,Andhra,Arabian,Argentine,Asian,Asian Fusion,Australian,Awadhi,...,Teriyaki,Tex-Mex,Thai,Tibetan,Turkish,Turkish Pizza,Vegetarian,Vietnamese,Western,World Cuisine
Restaurant Name,,,,,,,,,,,,,,,,,,,,,
'Ohana,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10 Downing Street,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11th Avenue Cafe Bistro,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
145 Kala Ghoda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19 Flavours Biryani,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
feel ALIVE,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
sketch Gallery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tashas,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
{Niche} - Cafe & Bar,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
�ukura��a Sofras۱,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
dfR['Restaurant Name'].sample(20, random_state=194)

504               Ceviche Tapas Bar & Restaurant
6926                            Delhi Club House
9273                                     Plot 17
9421                                        Zaoq
3996                   Lord of the Drinks Meadow
2311                                Olive Bistro
4088    Tian - Asian Cuisine Studio - ITC Maurya
9464                                      Marble
1419                            Cafe Soul Garden
6718                             The Headquarter
230                Red Ginger Sushi, Grill & Bar
3013                          Naturals Ice Cream
3094                                   Ardor 2.1
9415    Mr Cooper's House & Garden - The Midland
6426                                 Food Scouts
366                   Bosphorous Turkish Cuisine
2298                                  Three Guys
659                              The Cafe Baraco
592                               Hard Rock Cafe
4282                      Novelty Dairy & Stores
Name: Restaurant Name, dtype: object

In [24]:
from sklearn.metrics import jaccard_score

In [25]:


print(jaccard_score(restoXcuisines.loc["Olive Bistro"].values,
                    restoXcuisines.loc["Rose Cafe"].values))

0.3333333333333333

In [26]:
from scipy.spatial.distance import pdist, squareform

In [27]:


jaccardDist = pdist(restoXcuisines.values, metric='jaccard')
jaccardMatrix = squareform(jaccardDist)
jaccardSim = 1 - jaccardMatrix
dfJaccard = pd.DataFrame(
    jaccardSim,
    index=restoXcuisines.index,
    columns=restoXcuisines.index)

dfJaccard

Restaurant Name,'Ohana,10 Downing Street,11th Avenue Cafe Bistro,145 Kala Ghoda,19 Flavours Biryani,1918 Bistro & Grill,2 Dog,22nd Parallel,3 Wise Monkeys,38 Barracks,...,Zoeys Pizzeria,Zolocrust - Hotel Clarks Amer,Zombie Burger + Drink Lab,Zuka Choco-la,Zunzi's,feel ALIVE,sketch Gallery,tashas,{Niche} - Cafe & Bar,�ukura��a Sofras۱
Restaurant Name,,,,,,,,,,,,,,,,,,,,,
'Ohana,1.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00,0.000000,0.0,0.0,0.000000,0.0
10 Downing Street,0.0,1.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.000000,0.00,0.200000,0.0,0.0,0.500000,0.0
11th Avenue Cafe Bistro,0.0,0.0,1.000000,0.0,0.0,0.0,0.166667,0.0,0.0,0.333333,...,0.0,0.4,0.0,0.000000,0.00,0.142857,0.0,0.2,0.333333,0.0
145 Kala Ghoda,0.0,0.0,0.000000,1.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.2,0.333333,0.00,0.000000,0.0,0.0,0.000000,0.0
19 Flavours Biryani,0.0,0.0,0.000000,0.0,1.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00,0.000000,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
feel ALIVE,0.0,0.2,0.142857,0.0,0.0,0.0,0.166667,0.0,0.0,0.600000,...,0.0,0.0,0.0,0.000000,0.00,1.000000,0.0,0.0,0.142857,0.0
sketch Gallery,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00,0.000000,1.0,0.0,0.000000,0.0
tashas,0.0,0.0,0.200000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.25,0.000000,0.0,1.0,0.000000,0.0
{Niche} - Cafe & Bar,0.0,0.5,0.333333,0.0,0.0,0.0,0.000000,0.0,0.0,0.333333,...,0.0,0.4,0.0,0.000000,0.00,0.142857,0.0,0.0,1.000000,0.0
�ukura��a Sofras۱,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00,0.000000,0.0,0.0,0.000000,1.0

In [28]:


dfR['Restaurant Name'].sample(20)

2497                         R' ADDA
232            Jimmy's Pancake House
9293                     Fish Streat
258     Court Avenue Brewing Company
1869                   The Classroom
9282                      Union Deli
390                 The Grand Marlin
182                          Devotay
329                   Bonefish Grill
2343                             WTF
9454                          tashas
2685                          Kofuku
3111                  Smoke On Water
643                       Thaaliwala
75                           Paribar
3981                      Coast Cafe
3708                  The Sugar Cube
600           The Cheesecake Factory
7083            Elma's at Good Earth
9328                      Floriditas
Name: Restaurant Name, dtype: object

In [30]:


resto = 'Ooma'

resto = 'Ooma'

sim = dfJaccard.loc[resto].sort_values(ascending=False)
sim = pd.DataFrame({'Restaurant Name': sim.index, 'simScore': sim.values})
sim = sim[(sim['Restaurant Name']!= resto) & (sim['simScore']>=0.7)].head(5)
RestoRec = pd.merge(sim,dfR[['Restaurant Name','Aggregate rating']],how='inner',on='Restaurant Name')
FinalRestoRec = RestoRec.sort_values('Aggregate rating',ascending=False).drop_duplicates('Restaurant Name',keep='first')

In [31]:


FinalRestoRec

  Restaurant Name  simScore  Aggregate rating
3      Sushi Masa       1.0               4.9
7        Miyabi 9       1.0               4.8
8           Nagai       1.0               4.3
1           Osaka       1.0               4.2
5           Guppy       1.0               4.1